const labs = [
  {
    name: 'My First module final project - Snake Game',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'snake-game',
    type: 'Game',
    description: '',
    ext: 'png',
    path: 'https://alforsii.github.io/Snake-game-project-1/',
  },
  {
    name: 'Iron skydive',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'ironskydive',
    type: 'HTML/CSS',
    description: '',
    ext: 'png',
    path: './ironskydive/IronSkydive.html',
  },
  {
    name: 'Slack flexBox',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'slack',
    type: 'HTML/CSS',
    description:
      'Slack is a cloud-based set of team collaboration tools and services or in simpler terms, it is a chatting program.',
    ext: 'png',
    path: './lab-css-flexbox-slack/starter_code/index.html',
  },
  {
    name: 'Apple pie',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'apple-pie',
    type: 'HTML/CSS',
    description:
      'Cloning something that already exists is the best way to get better at front-end development.',
    ext: 'png',
    path:
      './lab-css-recipes-clone/starter-code/apple-pie-starter-code/index.html',
  },
  {
    name: 'Extra french soup',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'french-soup',
    type: 'HTML/CSS',
    description:
      'Cloning something that already exists is the best way to get better at front-end development.',
    ext: 'png',
    path: './lab-css-recipes-clone/starter-code/extra-french-soup/index.html',
  },
  {
    name: 'Revera cloning',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'revera',
    type: 'HTML/CSS',
    description:
      "Internet provides lots of templates and themes. But some of them cost money. However, we don't need to pay for something we already know how to do, so... We are cloning a theme!",
    ext: 'png',
    path: './lab-bootstrap-cloning-revera-master/starter-code/index.html',
  },
  {
    name: 'Instagram cloning',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'instagram',
    type: 'HTML/CSS',
    description:
      "One of the best ways to sharpen your CSS skills is to try to recreate an existing style and layout, so take a look at the deliverable below, work with a partner, and build your own version of Instagram.com. Don't worry if you can't get it to look exactly as you see but try your best to get as close as possible.",
    ext: 'png',
    path: './lab-css-instagram-clone-master/index.html',
  },
  {
    name: 'Spotify cloning_v1',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'spotify',
    type: 'HTML/CSS',
    description:
      "Everybody likes music, right? Odds are, if you do, you've heard of Spotify.",
    ext: 'png',
    path: './lab-css-spotify-clone-master/index.html',
  },
  {
    name: 'Spotify cloning_v2',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'spotify',
    type: 'HTML/CSS',
    description:
      "Everybody likes music, right? Odds are, if you do, you've heard of Spotify.",
    ext: 'png',
    path: './lab-css-spotify-clone/starter-code/index.html',
  },
  {
    name: 'Ironcart',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'ironcart',
    type: 'DOM manipulation with CSS and JavaScript',
    description:
      'IronCart - a shopping cart for the unofficial Ironhack merchandising store. Visitors should be able to add and remove products from the shopping cart, as well as to modify the number (quantity) of items that they want to purchase. Additionally, users should be able to see the subtotal and total price for the items they have added.',
    ext: 'png',
    path: './lab-dom-ironhack-cart-master/index.html',
  },
  {
    name: 'Pizza builder',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'pizza-builder',
    type: 'DOM manipulation with JavaScript',
    description:
      'We have got the munchies for a nice, fresh pie of pizza. Of course, we want to order online. After all, talking to a person will only delay the consumption of pizza.',
    ext: 'png',
    path: './lab-dom-pizza-builder-master/index.html',
  },
  {
    name: 'Memory Game',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'memory-game',
    type: 'Game - DOM manipulation with CSS and JavaScript',
    description:
      'To win, you needed to memorize the position of the paired card. Well, the logic of the game we will be building is the same.',
    ext: 'png',
    path: './lab-javascript-memory-game-master/index.html',
  },
  {
    name: 'Canvas crash course',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'canvas-animation',
    type: 'Game DOM manipulation with Canvas',
    description: '',
    ext: 'png',
    path: './my-canvas/index.html',
  },
  {
    name: 'Flappy birds',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'flappy-bird',
    type: 'Game DOM manipulation with Canvas',
    description:
      'The objective is to direct a flying bird, named "Faby", who moves continuously to the right, between sets of pipes. If the player touches the pipes, they lose. Faby briefly flaps upward each time that the player clicks on the spacebar; if the screen is not tapped, Faby falls because of gravity. If you want to understand better the game, go ahead and play a bit here',
    ext: 'png',
    path: './lab-canvas-flappybirds/starter_code/index.html',
  },
  {
    name: 'Hangman',
    completed: false,
    imgUrl: './labImages/',
    imgName: 'hangman',
    type: 'Game DOM manipulation with Canvas',
    description:
      'In this game, we have to figure out a secret word by guessing one letter at a time, with each error, the man will get one step closer to death! The goal is to successfully guess the word before the man gets hanged.',
    ext: 'png',
    path: './lab-canvas-hangman/starter_code/index.html',
  },
  {
    name: 'Race car',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'race-car',
    type: 'Game DOM manipulation with Canvas',
    description: 'Simple Games. Made with canvas in 2D context.',
    ext: 'png',
    path: './lab-canvas-race-car/starter_code/index.html',
  },
  {
    name: 'Basic algorithms-v1',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'basic-algorithms',
    type: 'Code',
    description:
      "The goal of this exercise is to get you familiarized with the primitive data structures in JavaScript, which we just covered in the class. Feel free to reference lesson materials and don't limit yourself but be curious and use Google to explore multiple solutions.",
    ext: 'png',
    path: './lab-javascript-basic-algorithms-v1/js/index.js',
  },
  {
    name: 'Basic algorithms-v2',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'basic-algorithms',
    type: 'Code',
    description:
      "The goal of this exercise is to get you familiarized with the primitive data structures in JavaScript, which we just covered in the class. Feel free to reference lesson materials and don't limit yourself but be curious and use Google to explore multiple solutions.",
    ext: 'png',
    path: './lab-javascript-basic-algorithms-v2/index.js',
  },
  {
    name: 'Advanced algorithms',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'advanced-algorithms',
    type: 'HTML/CSS/JavaScript',
    description:
      "In this exercise we will implement two different abstract data types that are very common: stacks and queues. Let's see what both data structures to understand how they work.",
    ext: 'png',
    path:
      './lab-javascript-advanced-algorithms/starter-code/DataStructures.html',
  },
  {
    name: 'Chronometer',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'chronometer',
    type: 'Code - DOM manipulation with Canvas',
    description:
      'Our Chronometer will have an LCD Screen, where we will see the minutes and seconds moving forward. It will also have two different buttons, that will change their behavior depending on the status of the Chronometer. For example, the start button will become stop button when the Chronometer is running.',
    ext: 'png',
    path: './lab-javascript-chronometer/starter-code/index.html',
  },
  {
    name: 'Clue',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'jsFile',
    type: 'Game - Code',
    description:
      "Do you remember the classic detective board game Clue? It was a very popular game in the 90's.The plot starts with the death of Mr. Boddy, the very wealthy owner of Tudor Manor. He was killed under highly suspicious circumstances, and it's the players mission to uncover which **suspect** murdered him, what **weapon** was used, and in which **room** of the mansion the crime took place.",
    ext: 'png',
    path: './lab-javascript-clue/src/clue.js',
  },
  {
    name: 'Functions and Arrays',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'jsFile',
    type: 'Code',
    description:
      'Manipulating arrays in code is a very common operation. Whether you are creating a total for a shopping cart, grabbing only the first names out of a list of people, or moving a piece on a chessboard, you are probably going to be modifying or manipulating an array in some way.',
    ext: 'png',
    path: './lab-javascript-functions-and-arrays/src/functions-and-arrays.js',
  },
  {
    name: 'Vikings',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'jsFile',
    type: 'Game - Code',
    description:
      'We must write the correct code in the src/viking.js file to make the test pass.',
    ext: 'png',
    path: './lab-javascript-vikings-master/src/viking.js',
  },
  {
    name: 'Greatest movies',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'jsFile',
    type: 'Code',
    description:
      'We have just learned some super useful methods, that will help us a lot to manipulate objects and arrays. In this exercise, we will focus on practicing them, and this being said, it is mandatory to implement at least one of them in each iteration.',
    ext: 'png',
    path: './lab-javascript-greatest-movies-master/src/movies.js',
  },
  {
    name: 'Acme web design cloning',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'acme',
    type: 'HTML/CSS',
    description: '',
    ext: 'png',
    path: './acme-web-design-clone/index.html',
  },
  {
    name: 'Wack a mole',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'wack-a-mole',
    type: 'Game - HTML/CSS/JavaScript',
    description:
      "It's famous game. You need to wack the mole to get score. If you miss you loose points. Good luck 👍.",
    ext: 'png',
    path: './my-wack-a-mole/index.html',
  },
  {
    name: 'Packman',
    completed: false,
    imgUrl: './labImages/',
    imgName: 'packman',
    type: 'Gama Animation - canvas',
    description: 'Canvas animation.',
    ext: 'png',
    path: './canvas-game-pacman-ghost/',
  },
  {
    name: 'NPM clone',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'npm-clone',
    type: 'HTML/CSS/',
    description: 'Cloning NPM.',
    ext: 'png',
    path: './newNPMclone/npm.html',
  },
  {
    name: 'Canvas basics',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'canvas-basics',
    type: 'HTML/CSS/JavaScript - canvas',
    description: 'Canvas basic practices.',
    ext: 'png',
    path: './canvas/canvas-basics/intro.html',
  },
  {
    name: 'Canvas lines',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'lines-curves',
    type: 'HTML/CSS/JavaScript - canvas',
    description: 'Canvas lines.',
    ext: 'png',
    path: './canvas/canvas-lines/canvas-lines.html',
  },
  {
    name: 'Canvas circles collision detection',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'circles-collision',
    type: 'HTML/CSS/JavaScript - canvas',
    description: 'Canvas circles collision detection.',
    ext: 'png',
    path: './canvas/collisionDetectio/index.html',
  },
  {
    name: 'Canvas motion particles',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'particles',
    type: 'HTML/CSS/JavaScript - canvas',
    description: 'Canvas motion particles',
    ext: 'png',
    path: './canvas/motion-partcles/index.html',
  },
  {
    name: 'Canvas bricks breaker',
    completed: 'partial',
    imgUrl: './labImages/',
    imgName: 'bricks-breaker',
    type: 'HTML/CSS/JavaScript - canvas',
    description: 'Canvas bricks breaker',
    ext: 'png',
    path: './canvas/newgame/index.html',
  },
  {
    name: 'Canvas sky shooter game',
    completed: 'partial',
    imgUrl: './labImages/',
    imgName: 'sky-shooter',
    type: 'HTML/CSS/JavaScript - canvas',
    description: 'Canvas sky shooting game',
    ext: 'png',
    path: './canvas/shooting-game/index.html',
  },
  {
    name: 'My BookList',
    completed: true,
    imgUrl: './labImages/',
    imgName: 'my-book-list',
    type: 'HTML/CSS/JavaScript - DOM manipulation',
    description: 'The book list. Add, remove, update and delete BookList.',
    ext: 'png',
    path: './bookListApp/index.html',
  },
];
